USE [master]
GO

/****** Object:  Database [skorka]    Script Date: 5/14/2015 7:40:59 PM ******/
CREATE DATABASE [skorka]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'skorka', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\skorka.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'skorka_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\skorka_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [skorka] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [skorka].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [skorka] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [skorka] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [skorka] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [skorka] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [skorka] SET ARITHABORT OFF 
GO

ALTER DATABASE [skorka] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [skorka] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [skorka] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [skorka] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [skorka] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [skorka] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [skorka] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [skorka] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [skorka] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [skorka] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [skorka] SET  DISABLE_BROKER 
GO

ALTER DATABASE [skorka] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [skorka] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [skorka] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [skorka] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [skorka] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [skorka] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [skorka] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [skorka] SET RECOVERY FULL 
GO

ALTER DATABASE [skorka] SET  MULTI_USER 
GO

ALTER DATABASE [skorka] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [skorka] SET DB_CHAINING OFF 
GO

ALTER DATABASE [skorka] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [skorka] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [skorka] SET  READ_WRITE 
GO

